# Data Preparation

## Import Libraries

In [ ]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

## Import Data
The dataset contains all available data for more than 800,000 consumer loans issued from 2007 to 2015 by Lending Club: a large US peer-to-peer lending company. There are several different versions of this dataset. We have used a version available on kaggle.com. A newer version of this dataset is available here: https://www.kaggle.com/datasets/adarshsng/lending-club-loan-data-csv

In [ ]:
date_columns = ['issue_d', 'last_pymnt_d', 'next_pymnt_d', 'last_credit_pull_d', 'hardship_start_date', 
         'hardship_end_date', 'payment_plan_start_date', 'debt_settlement_flag_date', 'settlement_date']

In [ ]:
loan_data_backup = pd.read_csv('loan.csv',low_memory=False, parse_dates=date_columns)

In [ ]:
loan_data = loan_data_backup.copy()

## Initial Data Exploration

In [ ]:
loan_data.shape

(2260668, 145)

In [ ]:
loan_data.dtypes.value_counts()

float64           105
object             27
datetime64[ns]      9
int64               4
dtype: int64

In [ ]:
# store the % missing values for each column
missing = loan_data.apply(lambda col: col.isnull()).sum().sort_values(ascending=False)/loan_data.shape[0]

In [ ]:
# looking at the columns that have more than 70% missing values
df_null = pd.DataFrame(missing, columns=['pct_missing'])
df_null[df_null['pct_missing']>0.7]

                                            pct_missing
id                                             1.000000
url                                            1.000000
member_id                                      1.000000
orig_projected_additional_accrued_interest     0.996273
hardship_length                                0.995305
hardship_reason                                0.995305
hardship_status                                0.995305
deferral_term                                  0.995305
hardship_amount                                0.995305
hardship_start_date                            0.995305
hardship_end_date                              0.995305
payment_plan_start_date                        0.995305
hardship_dpd                                   0.995305
hardship_loan_status                           0.995305
hardship_payoff_balance_amount                 0.995305
hardship_last_payment_amount                   0.995305
hardship_type                                  0.995305
debt_settlement_flag_date                      0.985378
settlement_status                              0.985378
settlement_date                                0.985378
settlement_amount                              0.985378
settlement_percentage                          0.985378
settlement_term                                0.985378
sec_app_mths_since_last_major_derog            0.984101
sec_app_revol_util                             0.953030
revol_bal_joint                                0.952218
sec_app_open_acc                               0.952217
sec_app_earliest_cr_line                       0.952217
sec_app_collections_12_mths_ex_med             0.952217
sec_app_chargeoff_within_12_mths               0.952217
sec_app_num_rev_accts                          0.952217
sec_app_open_act_il                            0.952217
sec_app_mort_acc                               0.952217
sec_app_inq_last_6mths                         0.952217
verification_status_joint                      0.948807
dti_joint                                      0.946606
annual_inc_joint                               0.946604
desc                                           0.944235
mths_since_last_record                         0.841128
mths_since_recent_bc_dlq                       0.770112
mths_since_last_major_derog                    0.743096

### Dropping columns with more than 70% null values

In [ ]:
drop_columns = list(missing[missing > 0.7].index)
df = loan_data.drop(columns=drop_columns)
print('We dropped {} columns'.format(len(drop_columns)))

We dropped 41 columns

In [ ]:
df.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2260668 entries, 0 to 2260667
Data columns (total 104 columns):
 #    Column                          Dtype
---   ------                          -----
 0    loan_amnt                       int64
 1    funded_amnt                     int64
 2    funded_amnt_inv                 float64
 3    term                            object
 4    int_rate                        float64
 5    installment                     float64
 6    grade                           object
 7    sub_grade                       object
 8    emp_title                       object
 9    emp_length                      object
 10   home_ownership                  object
 11   annual_inc                      float64
 12   verification_status             object
 13   issue_d                         datetime64[ns]
 14   loan_status                     object
 15   pymnt_plan                      object
 16   purpose                         object
 17   title                           object
 18   zip_code                        object
 19   addr_state                      object
 20   dti                             float64
 21   delinq_2yrs                     float64
 22   earliest_cr_line                object
 23   inq_last_6mths                  float64
 24   mths_since_last_delinq          float64
 25   open_acc                        float64
 26   pub_rec                         float64
 27   revol_bal                       int64
 28   revol_util                      float64
 29   total_acc                       float64
 30   initial_list_status             object
 31   out_prncp                       float64
 32   out_prncp_inv                   float64
 33   total_pymnt                     float64
 34   total_pymnt_inv                 float64
 35   total_rec_prncp                 float64
 36   total_rec_int                   float64
 37   total_rec_late_fee              float64
 38   recoveries                      float64
 39   collection_recovery_fee         float64
 40   last_pymnt_d                    datetime64[ns]
 41   last_pymnt_amnt                 float64
 42   next_pymnt_d                    datetime64[ns]
 43   last_credit_pull_d              datetime64[ns]
 44   collections_12_mths_ex_med      float64
 45   policy_code                     int64
 46   application_type                object
 47   acc_now_delinq                  float64
 48   tot_coll_amt                    float64
 49   tot_cur_bal                     float64
 50   open_acc_6m                     float64
 51   open_act_il                     float64
 52   open_il_12m                     float64
 53   open_il_24m                     float64
 54   mths_since_rcnt_il              float64
 55   total_bal_il                    float64
 56   il_util                         float64
 57   open_rv_12m                     float64
 58   open_rv_24m                     float64
 59   max_bal_bc                      float64
 60   all_util                        float64
 61   total_rev_hi_lim                float64
 62   inq_fi                          float64
 63   total_cu_tl                     float64
 64   inq_last_12m                    float64
 65   acc_open_past_24mths            float64
 66   avg_cur_bal                     float64
 67   bc_open_to_buy                  float64
 68   bc_util                         float64
 69   chargeoff_within_12_mths        float64
 70   delinq_amnt                     float64
 71   mo_sin_old_il_acct              float64
 72   mo_sin_old_rev_tl_op            float64
 73   mo_sin_rcnt_rev_tl_op           float64
 74   mo_sin_rcnt_tl                  float64
 75   mort_acc                        float64
 76   mths_since_recent_bc            float64
 77   mths_since_recent_inq           float64
 78   mths_since_recent_revol_delinq  float64
 79   num_accts_ever_120_pd           float64
 80   num_actv_bc_tl                  float64
 81   num_actv_rev_tl                 float64
 82   num_bc_sats                     float64
 83   num_bc_tl                       float64
 84   num_il_tl                       float64
 85   num_op_rev_tl                   float64
 86   num_rev_accts                   float64
 87   num_rev_tl_bal_gt_0             float64
 88   num_sats                        float64
 89   num_tl_120dpd_2m                float64
 90   num_tl_30dpd                    float64
 91   num_tl_90g_dpd_24m              float64
 92   num_tl_op_past_12m              float64
 93   pct_tl_nvr_dlq                  float64
 94   percent_bc_gt_75                float64
 95   pub_rec_bankruptcies            float64
 96   tax_liens                       float64
 97   tot_hi_cred_lim                 float64
 98   total_bal_ex_mort               float64
 99   total_bc_limit                  float64
 100  total_il_high_credit_limit      float64
 101  hardship_flag                   object
 102  disbursement_method             object
 103  debt_settlement_flag            object
dtypes: datetime64[ns](4), float64(77), int64(4), object(19)
memory usage: 1.8+ GB

In [ ]:
missing.sort_values()

addr_state                                    0.000000
verification_status                           0.000000
home_ownership                                0.000000
disbursement_method                           0.000000
sub_grade                                     0.000000
                                                ...
hardship_end_date                             0.995305
orig_projected_additional_accrued_interest    0.996273
member_id                                     1.000000
url                                           1.000000
id                                            1.000000
Length: 145, dtype: float64

In [ ]:
missing.index[63:113]

Index(['bc_util', 'percent_bc_gt_75', 'bc_open_to_buy', 'mths_since_recent_bc',
       'pct_tl_nvr_dlq', 'avg_cur_bal', 'mo_sin_old_rev_tl_op',
       'mo_sin_rcnt_rev_tl_op', 'num_rev_accts', 'num_bc_tl', 'num_actv_bc_tl',
       'num_accts_ever_120_pd', 'mo_sin_rcnt_tl', 'num_il_tl', 'num_op_rev_tl',
       'tot_coll_amt', 'num_rev_tl_bal_gt_0', 'total_rev_hi_lim',
       'tot_cur_bal', 'num_tl_30dpd', 'num_tl_90g_dpd_24m',
       'num_tl_op_past_12m', 'tot_hi_cred_lim', 'total_il_high_credit_limit',
       'num_actv_rev_tl', 'num_bc_sats', 'num_sats', 'total_bal_ex_mort',
       'total_bc_limit', 'mort_acc', 'acc_open_past_24mths', 'title',
       'last_pymnt_d', 'revol_util', 'dti', 'pub_rec_bankruptcies',
       'collections_12_mths_ex_med', 'chargeoff_within_12_mths', 'tax_liens',
       'last_credit_pull_d', 'inq_last_6mths', 'open_acc', 'total_acc',
       'delinq_amnt', 'pub_rec', 'acc_now_delinq', 'earliest_cr_line',
       'delinq_2yrs', 'annual_inc', 'zip_code'],
      dtype='object')

In [ ]:
df.dropna(subset=missing.index[63:113],inplace=True,how="any")

In [ ]:
df.dropna(subset=["mo_sin_old_il_acct", "num_tl_120dpd_2m"],inplace=True,how="any")

In [ ]:
df.shape

(1991265, 104)

In [ ]:
df["emp_title"].value_counts()

Teacher                         36149
Manager                         31343
Owner                           19410
Registered Nurse                14676
RN                              13745
                                ...
aquatics director                   1
Senior Real Estate Paralegal        1
Sergeant/Law Enforcement            1
Accountant/Server                   1
Sales, Estimating & Design          1
Name: emp_title, Length: 441835, dtype: int64

In [ ]:
missing.index[41:62]

Index(['mths_since_recent_revol_delinq', 'next_pymnt_d',
       'mths_since_last_delinq', 'il_util', 'mths_since_rcnt_il', 'all_util',
       'open_acc_6m', 'inq_last_12m', 'total_cu_tl', 'total_bal_il',
       'open_rv_12m', 'inq_fi', 'max_bal_bc', 'open_rv_24m', 'open_act_il',
       'open_il_12m', 'open_il_24m', 'mths_since_recent_inq', 'emp_title',
       'num_tl_120dpd_2m', 'emp_length'],
      dtype='object')

In [ ]:
df1=df.drop(missing.index[41:62],axis=1)

In [ ]:
df1.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1991265 entries, 0 to 2260666
Data columns (total 83 columns):
 #   Column                      Dtype
---  ------                      -----
 0   loan_amnt                   int64
 1   funded_amnt                 int64
 2   funded_amnt_inv             float64
 3   term                        object
 4   int_rate                    float64
 5   installment                 float64
 6   grade                       object
 7   sub_grade                   object
 8   home_ownership              object
 9   annual_inc                  float64
 10  verification_status         object
 11  issue_d                     datetime64[ns]
 12  loan_status                 object
 13  pymnt_plan                  object
 14  purpose                     object
 15  title                       object
 16  zip_code                    object
 17  addr_state                  object
 18  dti                         float64
 19  delinq_2yrs                 float64
 20  earliest_cr_line            object
 21  inq_last_6mths              float64
 22  open_acc                    float64
 23  pub_rec                     float64
 24  revol_bal                   int64
 25  revol_util                  float64
 26  total_acc                   float64
 27  initial_list_status         object
 28  out_prncp                   float64
 29  out_prncp_inv               float64
 30  total_pymnt                 float64
 31  total_pymnt_inv             float64
 32  total_rec_prncp             float64
 33  total_rec_int               float64
 34  total_rec_late_fee          float64
 35  recoveries                  float64
 36  collection_recovery_fee     float64
 37  last_pymnt_d                datetime64[ns]
 38  last_pymnt_amnt             float64
 39  last_credit_pull_d          datetime64[ns]
 40  collections_12_mths_ex_med  float64
 41  policy_code                 int64
 42  application_type            object
 43  acc_now_delinq              float64
 44  tot_coll_amt                float64
 45  tot_cur_bal                 float64
 46  total_rev_hi_lim            float64
 47  acc_open_past_24mths        float64
 48  avg_cur_bal                 float64
 49  bc_open_to_buy              float64
 50  bc_util                     float64
 51  chargeoff_within_12_mths    float64
 52  delinq_amnt                 float64
 53  mo_sin_old_il_acct          float64
 54  mo_sin_old_rev_tl_op        float64
 55  mo_sin_rcnt_rev_tl_op       float64
 56  mo_sin_rcnt_tl              float64
 57  mort_acc                    float64
 58  mths_since_recent_bc        float64
 59  num_accts_ever_120_pd       float64
 60  num_actv_bc_tl              float64
 61  num_actv_rev_tl             float64
 62  num_bc_sats                 float64
 63  num_bc_tl                   float64
 64  num_il_tl                   float64
 65  num_op_rev_tl               float64
 66  num_rev_accts               float64
 67  num_rev_tl_bal_gt_0         float64
 68  num_sats                    float64
 69  num_tl_30dpd                float64
 70  num_tl_90g_dpd_24m          float64
 71  num_tl_op_past_12m          float64
 72  pct_tl_nvr_dlq              float64
 73  percent_bc_gt_75            float64
 74  pub_rec_bankruptcies        float64
 75  tax_liens                   float64
 76  tot_hi_cred_lim             float64
 77  total_bal_ex_mort           float64
 78  total_bc_limit              float64
 79  total_il_high_credit_limit  float64
 80  hardship_flag               object
 81  disbursement_method         object
 82  debt_settlement_flag        object
dtypes: datetime64[ns](3), float64(59), int64(4), object(17)
memory usage: 1.2+ GB

In [ ]:
#pd.pandas.set_option('display.max_rows', None)

In [ ]:
#df.isnull().sum().sort_values()

In [ ]:
#df.to_csv("Loan_Data_withnull.csv")

In [ ]:
#df1.to_csv("Loan_Data_wonull.csv")

In [ ]:
len(df1["grade"].value_counts())

7

In [ ]:
df1["application_type"].value_counts()

Individual    1880068
Joint App      111197
Name: application_type, dtype: int64

In [ ]:
df1=df1.drop(["title","zip_code","addr_state","sub_grade"],axis=1)

In [ ]:
df1.shape

(1991265, 79)

In [ ]:
df1=df1.drop(['last_pymnt_d', 'last_credit_pull_d'],axis=1)

### TERM COLUMN

In [ ]:
df1['term']

0           36 months
1           60 months
2           36 months
3           36 months
4           60 months
              ...
2260662     60 months
2260663     60 months
2260664     60 months
2260665     36 months
2260666     60 months
Name: term, Length: 1991265, dtype: object

In [ ]:
# Replace unwanted sub-strings and capture results in a new column
df1['term_int'] = df1['term'].str.replace(' months', '')

In [ ]:
df1['term_int']

0           36
1           60
2           36
3           36
4           60
          ...
2260662     60
2260663     60
2260664     60
2260665     36
2260666     60
Name: term_int, Length: 1991265, dtype: object

In [ ]:
# Change the type of the column to numeric
df1['term_int'] = pd.to_numeric(df1['term_int'])

In [ ]:
df1=df1.drop(["term"],axis=1)

### DATE COLUMNS

In [ ]:
df1['issue_d'] = pd.to_datetime(df1['issue_d'], format = '%b-%y')

In [ ]:
df1['mths_since_issue_d'] = round(pd.to_numeric((pd.to_datetime('2017-12-01') - df1['issue_d']) / np.timedelta64(1, 'M')))

In [ ]:
df1['mths_since_issue_d'].describe()

count    1.991265e+06
mean     1.713743e+01
std      1.914071e+01
min     -1.200000e+01
25%      1.000000e+00
50%      1.600000e+01
75%      3.100000e+01
max      6.400000e+01
Name: mths_since_issue_d, dtype: float64

In [ ]:
# replace negative values with max value
df1['mths_since_issue_d'][df1['mths_since_issue_d'] < 0] = df1['mths_since_issue_d'].max()

In [ ]:
df1['mths_since_issue_d'].describe()

count    1.991265e+06
mean     3.334755e+01
std      2.178537e+01
min      0.000000e+00
25%      1.500000e+01
50%      2.900000e+01
75%      5.700000e+01
max      6.400000e+01
Name: mths_since_issue_d, dtype: float64

In [ ]:
df1=df1.drop("issue_d",axis=1)

In [ ]:
df1["earliest_cr_line"]

0          Apr-2001
1          Jun-1987
2          Apr-2011
3          Feb-2006
4          Dec-2000
             ...
2260662    Aug-1996
2260663    Jan-2004
2260664    Mar-2003
2260665    Feb-1995
2260666    Jul-2003
Name: earliest_cr_line, Length: 1991265, dtype: object

In [ ]:
df1["earliest_cr_line"].isna().sum()

0

In [ ]:
df1['earliest_cr_line_date'] = pd.to_datetime(df1['earliest_cr_line'],format = '%b-%Y')

In [ ]:
df1["earliest_cr_line_date"].value_counts()

2004-09-01    14078
2003-09-01    13866
2005-09-01    13522
2003-08-01    13367
2004-08-01    13147
              ...
1955-08-01        1
1941-08-01        1
1952-11-01        1
1953-08-01        1
1956-06-01        1
Name: earliest_cr_line_date, Length: 749, dtype: int64

In [ ]:
df1['mths_since_earliest_cr_line'] = round(pd.to_numeric((pd.to_datetime('2017-12-01') - df1['earliest_cr_line_date']) / np.timedelta64(1, 'M')))

In [ ]:
df1['mths_since_earliest_cr_line'].describe()

count    1.991265e+06
mean     2.145852e+02
std      9.317453e+01
min      2.500000e+01
25%      1.510000e+02
50%      1.980000e+02
75%      2.630000e+02
max      1.017000e+03
Name: mths_since_earliest_cr_line, dtype: float64

In [ ]:
df1=df1.drop(["earliest_cr_line_date","earliest_cr_line"],axis=1)

In [ ]:
df1.shape

(1991265, 77)

In [ ]:
df1.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1991265 entries, 0 to 2260666
Data columns (total 77 columns):
 #   Column                       Dtype
---  ------                       -----
 0   loan_amnt                    int64
 1   funded_amnt                  int64
 2   funded_amnt_inv              float64
 3   int_rate                     float64
 4   installment                  float64
 5   grade                        object
 6   home_ownership               object
 7   annual_inc                   float64
 8   verification_status          object
 9   loan_status                  object
 10  pymnt_plan                   object
 11  purpose                      object
 12  dti                          float64
 13  delinq_2yrs                  float64
 14  inq_last_6mths               float64
 15  open_acc                     float64
 16  pub_rec                      float64
 17  revol_bal                    int64
 18  revol_util                   float64
 19  total_acc                    float64
 20  initial_list_status          object
 21  out_prncp                    float64
 22  out_prncp_inv                float64
 23  total_pymnt                  float64
 24  total_pymnt_inv              float64
 25  total_rec_prncp              float64
 26  total_rec_int                float64
 27  total_rec_late_fee           float64
 28  recoveries                   float64
 29  collection_recovery_fee      float64
 30  last_pymnt_amnt              float64
 31  collections_12_mths_ex_med   float64
 32  policy_code                  int64
 33  application_type             object
 34  acc_now_delinq               float64
 35  tot_coll_amt                 float64
 36  tot_cur_bal                  float64
 37  total_rev_hi_lim             float64
 38  acc_open_past_24mths         float64
 39  avg_cur_bal                  float64
 40  bc_open_to_buy               float64
 41  bc_util                      float64
 42  chargeoff_within_12_mths     float64
 43  delinq_amnt                  float64
 44  mo_sin_old_il_acct           float64
 45  mo_sin_old_rev_tl_op         float64
 46  mo_sin_rcnt_rev_tl_op        float64
 47  mo_sin_rcnt_tl               float64
 48  mort_acc                     float64
 49  mths_since_recent_bc         float64
 50  num_accts_ever_120_pd        float64
 51  num_actv_bc_tl               float64
 52  num_actv_rev_tl              float64
 53  num_bc_sats                  float64
 54  num_bc_tl                    float64
 55  num_il_tl                    float64
 56  num_op_rev_tl                float64
 57  num_rev_accts                float64
 58  num_rev_tl_bal_gt_0          float64
 59  num_sats                     float64
 60  num_tl_30dpd                 float64
 61  num_tl_90g_dpd_24m           float64
 62  num_tl_op_past_12m           float64
 63  pct_tl_nvr_dlq               float64
 64  percent_bc_gt_75             float64
 65  pub_rec_bankruptcies         float64
 66  tax_liens                    float64
 67  tot_hi_cred_lim              float64
 68  total_bal_ex_mort            float64
 69  total_bc_limit               float64
 70  total_il_high_credit_limit   float64
 71  hardship_flag                object
 72  disbursement_method          object
 73  debt_settlement_flag         object
 74  term_int                     int64
 75  mths_since_issue_d           float64
 76  mths_since_earliest_cr_line  float64
dtypes: float64(61), int64(5), object(11)
memory usage: 1.2+ GB

In [ ]:
numericaln = []
categoricaln = []
datesn = []

for col in list(df1.columns):
    if df1[col].dtype == "float64" or df1[col].dtype == "int64":
        numericaln.append(col)
    elif df1[col].dtype == "object":
        categoricaln.append(col) 
    elif df1[col].dtype == "<M8[ns]":
        datesn.append(col)

In [ ]:
numconnt=[]
numdisc=[]
for i in numericaln:
    if len(df1[i].value_counts()) > 5:
        numconnt.append(i)
    else:
        numdisc.append(i)

In [ ]:
len(numconnt)

63

In [ ]:
len(numdisc)

3

In [ ]:
df1["loan_status"].value_counts()

Fully Paid            901309
Current               837921
Charged Off           221806
Late (31-120 days)     18975
In Grace Period         7970
Late (16-30 days)       3256
Default                   28
Name: loan_status, dtype: int64

In [ ]:
df1['good_bad'] = np.where(df['loan_status'].isin(['Charged Off', 'Default','Late (31-120 days)',"In Grace Period"]), 0, 1)

In [ ]:
df1["good_bad"].value_counts()

1    1742486
0     248779
Name: good_bad, dtype: int64

In [ ]:
df1.shape

(1991265, 78)

In [ ]:
df1.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1991265 entries, 0 to 2260666
Data columns (total 78 columns):
 #   Column                       Dtype
---  ------                       -----
 0   loan_amnt                    int64
 1   funded_amnt                  int64
 2   funded_amnt_inv              float64
 3   int_rate                     float64
 4   installment                  float64
 5   grade                        object
 6   home_ownership               object
 7   annual_inc                   float64
 8   verification_status          object
 9   loan_status                  object
 10  pymnt_plan                   object
 11  purpose                      object
 12  dti                          float64
 13  delinq_2yrs                  float64
 14  inq_last_6mths               float64
 15  open_acc                     float64
 16  pub_rec                      float64
 17  revol_bal                    int64
 18  revol_util                   float64
 19  total_acc                    float64
 20  initial_list_status          object
 21  out_prncp                    float64
 22  out_prncp_inv                float64
 23  total_pymnt                  float64
 24  total_pymnt_inv              float64
 25  total_rec_prncp              float64
 26  total_rec_int                float64
 27  total_rec_late_fee           float64
 28  recoveries                   float64
 29  collection_recovery_fee      float64
 30  last_pymnt_amnt              float64
 31  collections_12_mths_ex_med   float64
 32  policy_code                  int64
 33  application_type             object
 34  acc_now_delinq               float64
 35  tot_coll_amt                 float64
 36  tot_cur_bal                  float64
 37  total_rev_hi_lim             float64
 38  acc_open_past_24mths         float64
 39  avg_cur_bal                  float64
 40  bc_open_to_buy               float64
 41  bc_util                      float64
 42  chargeoff_within_12_mths     float64
 43  delinq_amnt                  float64
 44  mo_sin_old_il_acct           float64
 45  mo_sin_old_rev_tl_op         float64
 46  mo_sin_rcnt_rev_tl_op        float64
 47  mo_sin_rcnt_tl               float64
 48  mort_acc                     float64
 49  mths_since_recent_bc         float64
 50  num_accts_ever_120_pd        float64
 51  num_actv_bc_tl               float64
 52  num_actv_rev_tl              float64
 53  num_bc_sats                  float64
 54  num_bc_tl                    float64
 55  num_il_tl                    float64
 56  num_op_rev_tl                float64
 57  num_rev_accts                float64
 58  num_rev_tl_bal_gt_0          float64
 59  num_sats                     float64
 60  num_tl_30dpd                 float64
 61  num_tl_90g_dpd_24m           float64
 62  num_tl_op_past_12m           float64
 63  pct_tl_nvr_dlq               float64
 64  percent_bc_gt_75             float64
 65  pub_rec_bankruptcies         float64
 66  tax_liens                    float64
 67  tot_hi_cred_lim              float64
 68  total_bal_ex_mort            float64
 69  total_bc_limit               float64
 70  total_il_high_credit_limit   float64
 71  hardship_flag                object
 72  disbursement_method          object
 73  debt_settlement_flag         object
 74  term_int                     int64
 75  mths_since_issue_d           float64
 76  mths_since_earliest_cr_line  float64
 77  good_bad                     int32
dtypes: float64(61), int32(1), int64(5), object(11)
memory usage: 1.2+ GB

In [ ]:
df1=df1.drop(["recoveries","total_rec_prncp","total_rec_int","total_rec_late_fee","collection_recovery_fee",
          "debt_settlement_flag","hardship_flag","policy_code"],axis=1)

In [ ]:
df1.shape

(1991265, 70)

In [ ]:
#df1.to_csv("WOE_calc2.csv")